# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions
name: deploy for warbler-fe

on:
  push:
    branches:
      - 'main' # 只针对 main 分支
    paths:
      - 'dist/**'
      - '.github/workflows/*'
      # - 'husky/**'
      # - '.vscode/**'
      # - 'Docker/**'
      # - 'public/**'
      # - 'src/**'
      #

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "82.156.231.91" >> ~/.ssh/known_hosts
      - name: deploy # 部署
        run: |
          ssh root@82.156.231.91 "
            cd /home/work/imooc-lego/biz-editer-server;
            git remote add origin https://${{secrets.WFP_TOKEN}}@github.com/alanhzw/biz-editer-server.git;
            git checkout dev;
            git pull origin dev; # 重新下载最新代码
            git remote remove origin; # 删除 origin ，否则会暴露 github 密码
            # 启动 docker
            docker compose build editor-server; # 和 docker-compose.yml service 名字一致
            docker compose up -d;
          "
      - name: delete ssh key # 删除 ssh key
        run: rm -rf ~/.ssh/id_rsa
