# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions
name: deploy for warbler-fe

on:
  push:
    branches:
      - 'main' # 只针对 main 分支
    paths:
      - 'dist/**'
      - '.github/workflows/*'
      # - 'husky/**'
      # - '.vscode/**'
      # - 'Docker/**'
      # - 'public/**'
      # - 'src/**'
      #

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+jLLmqpzmSTQs/hibFZnpOHYJdmdL3Fhmsa8Kn25dIgepVFv6l8csYWb58ir/j5NegKKCykH7BthGBjVlCKx8ns1sErFNYVe9Ngp1jd3r/7qhnpYZcVBBeGNLcd7VTL+3mG3iT5MYlh4x/Wxq9AtzWh2ti3A97fAuZ7ZEp1o5kPI7zX7WK7c/cm3XMndj8KnrU2B6iCeAtE/p0Qs9jlqFSDLATSKi/KuHhj/UvrRR14IlKln/YPwkxD4CewVPh5yRWhgtigYmxeK7r5CV2BNyfv2Qh6YnEygmK75vE6PNCfinoHGcuzVuAXNjA0wxQizoUxZ7Bi+YeB+2Z8wqjbbYpPfg5gJsJAbZMPnXHGmOBbO5SwkNDBy7An+hCB1sVgwL/8yjvJRjMwzuUCmE+0JiwY9/J//+ZUwqmNkgbS+EDYTWnAeDEb7feriN1CmhbPRIObTRKODdvte6iuBQwRmzg/SbebKrHJpnxSmr+R//igSmbzkhP78CtvD6SoCqga8= alanHzw@1741847465@qq.com" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "82.156.231.91" >> ~/.ssh/known_hosts
      - name: deploy # 部署
        run: |
          ssh root@82.156.231.91 "
            cd /home/work/warbler-fe/warbler-fe;
            git pull;
            docker cp dist 7475501d0da5:/usr/share/nginx/fe/;
          "
